# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: db_service_metadata.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
import data_metadatas_pb2 as data__metadatas__pb2
import data_types_pb2 as data__types__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='db_service_metadata.proto',
  package='io.lightcone.services.metadata_service',
  syntax='proto3',
  serialized_options=_b('P\001'),
  serialized_pb=_b('\n\x19\x64\x62_service_metadata.proto\x12&io.lightcone.services.metadata_service\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x14\x64\x61ta_metadatas.proto\x1a\x10\x64\x61ta_types.proto\"\x1f\n\x0cGetTokensReq\x12\x0f\n\x07symbols\x18\x01 \x03(\t\"p\n\x0cGetTokensRes\x12\x31\n\x06tokens\x18\x01 \x03(\x0b\x32!.io.lightcone.data.metadata.Token\x12-\n\x05\x65rror\x18\x02 \x01(\x0b\x32\x1e.io.lightcone.data.types.Error\" \n\rGetMarketsReq\x12\x0f\n\x07symbols\x18\x01 \x03(\t\"s\n\rGetMarketsRes\x12\x33\n\x07markets\x18\x01 \x03(\x0b\x32\".io.lightcone.data.metadata.Market\x12-\n\x05\x65rror\x18\x02 \x01(\x0b\x32\x1e.io.lightcone.data.types.Error\"\xc6\x01\n\x10GetCurrenciesRes\x12T\n\x06prices\x18\x01 \x03(\x0b\x32\x44.io.lightcone.services.metadata_service.GetCurrenciesRes.PricesEntry\x12-\n\x05\x65rror\x18\x02 \x01(\x0b\x32\x1e.io.lightcone.data.types.Error\x1a-\n\x0bPricesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01:\x02\x38\x01\x32\xaa\x03\n\x0fMetadataService\x12?\n\rsyncMetadatas\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12w\n\tgetTokens\x12\x34.io.lightcone.services.metadata_service.GetTokensReq\x1a\x34.io.lightcone.services.metadata_service.GetTokensRes\x12z\n\ngetMarkets\x12\x35.io.lightcone.services.metadata_service.GetMarketsReq\x1a\x35.io.lightcone.services.metadata_service.GetMarketsRes\x12\x61\n\rgetCurrencies\x12\x16.google.protobuf.Empty\x1a\x38.io.lightcone.services.metadata_service.GetCurrenciesResB\x02P\x01\x62\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,google_dot_protobuf_dot_wrappers__pb2.DESCRIPTOR,data__metadatas__pb2.DESCRIPTOR,data__types__pb2.DESCRIPTOR,])




_GETTOKENSREQ = _descriptor.Descriptor(
  name='GetTokensReq',
  full_name='io.lightcone.services.metadata_service.GetTokensReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='symbols', full_name='io.lightcone.services.metadata_service.GetTokensReq.symbols', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=170,
  serialized_end=201,
)


_GETTOKENSRES = _descriptor.Descriptor(
  name='GetTokensRes',
  full_name='io.lightcone.services.metadata_service.GetTokensRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tokens', full_name='io.lightcone.services.metadata_service.GetTokensRes.tokens', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error', full_name='io.lightcone.services.metadata_service.GetTokensRes.error', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=203,
  serialized_end=315,
)


_GETMARKETSREQ = _descriptor.Descriptor(
  name='GetMarketsReq',
  full_name='io.lightcone.services.metadata_service.GetMarketsReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='symbols', full_name='io.lightcone.services.metadata_service.GetMarketsReq.symbols', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=317,
  serialized_end=349,
)


_GETMARKETSRES = _descriptor.Descriptor(
  name='GetMarketsRes',
  full_name='io.lightcone.services.metadata_service.GetMarketsRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='markets', full_name='io.lightcone.services.metadata_service.GetMarketsRes.markets', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error', full_name='io.lightcone.services.metadata_service.GetMarketsRes.error', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=351,
  serialized_end=466,
)


_GETCURRENCIESRES_PRICESENTRY = _descriptor.Descriptor(
  name='PricesEntry',
  full_name='io.lightcone.services.metadata_service.GetCurrenciesRes.PricesEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='io.lightcone.services.metadata_service.GetCurrenciesRes.PricesEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='io.lightcone.services.metadata_service.GetCurrenciesRes.PricesEntry.value', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=622,
  serialized_end=667,
)

_GETCURRENCIESRES = _descriptor.Descriptor(
  name='GetCurrenciesRes',
  full_name='io.lightcone.services.metadata_service.GetCurrenciesRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='prices', full_name='io.lightcone.services.metadata_service.GetCurrenciesRes.prices', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error', full_name='io.lightcone.services.metadata_service.GetCurrenciesRes.error', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_GETCURRENCIESRES_PRICESENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=469,
  serialized_end=667,
)

_GETTOKENSRES.fields_by_name['tokens'].message_type = data__metadatas__pb2._TOKEN
_GETTOKENSRES.fields_by_name['error'].message_type = data__types__pb2._ERROR
_GETMARKETSRES.fields_by_name['markets'].message_type = data__metadatas__pb2._MARKET
_GETMARKETSRES.fields_by_name['error'].message_type = data__types__pb2._ERROR
_GETCURRENCIESRES_PRICESENTRY.containing_type = _GETCURRENCIESRES
_GETCURRENCIESRES.fields_by_name['prices'].message_type = _GETCURRENCIESRES_PRICESENTRY
_GETCURRENCIESRES.fields_by_name['error'].message_type = data__types__pb2._ERROR
DESCRIPTOR.message_types_by_name['GetTokensReq'] = _GETTOKENSREQ
DESCRIPTOR.message_types_by_name['GetTokensRes'] = _GETTOKENSRES
DESCRIPTOR.message_types_by_name['GetMarketsReq'] = _GETMARKETSREQ
DESCRIPTOR.message_types_by_name['GetMarketsRes'] = _GETMARKETSRES
DESCRIPTOR.message_types_by_name['GetCurrenciesRes'] = _GETCURRENCIESRES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetTokensReq = _reflection.GeneratedProtocolMessageType('GetTokensReq', (_message.Message,), {
  'DESCRIPTOR' : _GETTOKENSREQ,
  '__module__' : 'db_service_metadata_pb2'
  # @@protoc_insertion_point(class_scope:io.lightcone.services.metadata_service.GetTokensReq)
  })
_sym_db.RegisterMessage(GetTokensReq)

GetTokensRes = _reflection.GeneratedProtocolMessageType('GetTokensRes', (_message.Message,), {
  'DESCRIPTOR' : _GETTOKENSRES,
  '__module__' : 'db_service_metadata_pb2'
  # @@protoc_insertion_point(class_scope:io.lightcone.services.metadata_service.GetTokensRes)
  })
_sym_db.RegisterMessage(GetTokensRes)

GetMarketsReq = _reflection.GeneratedProtocolMessageType('GetMarketsReq', (_message.Message,), {
  'DESCRIPTOR' : _GETMARKETSREQ,
  '__module__' : 'db_service_metadata_pb2'
  # @@protoc_insertion_point(class_scope:io.lightcone.services.metadata_service.GetMarketsReq)
  })
_sym_db.RegisterMessage(GetMarketsReq)

GetMarketsRes = _reflection.GeneratedProtocolMessageType('GetMarketsRes', (_message.Message,), {
  'DESCRIPTOR' : _GETMARKETSRES,
  '__module__' : 'db_service_metadata_pb2'
  # @@protoc_insertion_point(class_scope:io.lightcone.services.metadata_service.GetMarketsRes)
  })
_sym_db.RegisterMessage(GetMarketsRes)

GetCurrenciesRes = _reflection.GeneratedProtocolMessageType('GetCurrenciesRes', (_message.Message,), {

  'PricesEntry' : _reflection.GeneratedProtocolMessageType('PricesEntry', (_message.Message,), {
    'DESCRIPTOR' : _GETCURRENCIESRES_PRICESENTRY,
    '__module__' : 'db_service_metadata_pb2'
    # @@protoc_insertion_point(class_scope:io.lightcone.services.metadata_service.GetCurrenciesRes.PricesEntry)
    })
  ,
  'DESCRIPTOR' : _GETCURRENCIESRES,
  '__module__' : 'db_service_metadata_pb2'
  # @@protoc_insertion_point(class_scope:io.lightcone.services.metadata_service.GetCurrenciesRes)
  })
_sym_db.RegisterMessage(GetCurrenciesRes)
_sym_db.RegisterMessage(GetCurrenciesRes.PricesEntry)


DESCRIPTOR._options = None
_GETCURRENCIESRES_PRICESENTRY._options = None

_METADATASERVICE = _descriptor.ServiceDescriptor(
  name='MetadataService',
  full_name='io.lightcone.services.metadata_service.MetadataService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=670,
  serialized_end=1096,
  methods=[
  _descriptor.MethodDescriptor(
    name='syncMetadatas',
    full_name='io.lightcone.services.metadata_service.MetadataService.syncMetadatas',
    index=0,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='getTokens',
    full_name='io.lightcone.services.metadata_service.MetadataService.getTokens',
    index=1,
    containing_service=None,
    input_type=_GETTOKENSREQ,
    output_type=_GETTOKENSRES,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='getMarkets',
    full_name='io.lightcone.services.metadata_service.MetadataService.getMarkets',
    index=2,
    containing_service=None,
    input_type=_GETMARKETSREQ,
    output_type=_GETMARKETSRES,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='getCurrencies',
    full_name='io.lightcone.services.metadata_service.MetadataService.getCurrencies',
    index=3,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_GETCURRENCIESRES,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_METADATASERVICE)

DESCRIPTOR.services_by_name['MetadataService'] = _METADATASERVICE

# @@protoc_insertion_point(module_scope)
