# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: db_service_onchain_withdrawals.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
import data_requests_pb2 as data__requests__pb2
import data_types_pb2 as data__types__pb2
import data_events_pb2 as data__events__pb2
import db_service_request_common_pb2 as db__service__request__common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='db_service_onchain_withdrawals.proto',
  package='io.lightcone.services.onchain_withdrawals_db_service',
  syntax='proto3',
  serialized_options=_b('P\001'),
  serialized_pb=_b('\n$db_service_onchain_withdrawals.proto\x12\x34io.lightcone.services.onchain_withdrawals_db_service\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x13\x64\x61ta_requests.proto\x1a\x10\x64\x61ta_types.proto\x1a\x11\x64\x61ta_events.proto\x1a\x1f\x64\x62_service_request_common.proto\"\x9e\x01\n\x12GetUserRequestsRes\x12\x46\n\x08requests\x18\x01 \x03(\x0b\x32\x34.io.lightcone.data.requests.OnchainWithdrawalRequest\x12\x11\n\ttotal_num\x18\x02 \x01(\r\x12-\n\x05\x65rror\x18\x03 \x01(\x0b\x32\x1e.io.lightcone.data.types.Error\"\x87\x01\n\x0eGetRequestsRes\x12\x46\n\x08requests\x18\x01 \x03(\x0b\x32\x34.io.lightcone.data.requests.OnchainWithdrawalRequest\x12-\n\x05\x65rror\x18\x02 \x01(\x0b\x32\x1e.io.lightcone.data.types.Error\"[\n\x11SubmitRequestsReq\x12\x46\n\x08requests\x18\x01 \x03(\x0b\x32\x34.io.lightcone.data.requests.OnchainWithdrawalRequest2\xfb\x06\n\x1bOnchainWithdrawalsDBService\x12\x95\x01\n\x0fgetUserRequests\x12\x38.io.lightcone.services.request.common.GetUserRequestsReq\x1aH.io.lightcone.services.onchain_withdrawals_db_service.GetUserRequestsRes\x12V\n\x08getStats\x12\x16.google.protobuf.Empty\x1a\x32.io.lightcone.services.request.common.RequestStats\x12\x8d\x01\n\x0fgetRequestByIds\x12\x34.io.lightcone.services.request.common.GetRequestsReq\x1a\x44.io.lightcone.services.onchain_withdrawals_db_service.GetRequestsRes\x12\x42\n\x10startAggregating\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12|\n\x0cgetByBlockId\x12\x35.io.lightcone.services.request.common.GetByBlockIdReq\x1a\x35.io.lightcone.services.request.common.GetByBlockIdRes\x12\x8b\x01\n\x17updateTxHashesAndStatus\x12\x37.io.lightcone.services.request.common.UpdateTxHashesReq\x1a\x37.io.lightcone.services.request.common.UpdateTxHashesRes\x12\x8b\x01\n\x11\x66inishDistributed\x12:.io.lightcone.services.request.common.FinishDistributedReq\x1a:.io.lightcone.services.request.common.FinishDistributedResB\x02P\x01\x62\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,google_dot_protobuf_dot_wrappers__pb2.DESCRIPTOR,data__requests__pb2.DESCRIPTOR,data__types__pb2.DESCRIPTOR,data__events__pb2.DESCRIPTOR,db__service__request__common__pb2.DESCRIPTOR,])




_GETUSERREQUESTSRES = _descriptor.Descriptor(
  name='GetUserRequestsRes',
  full_name='io.lightcone.services.onchain_withdrawals_db_service.GetUserRequestsRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='requests', full_name='io.lightcone.services.onchain_withdrawals_db_service.GetUserRequestsRes.requests', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='total_num', full_name='io.lightcone.services.onchain_withdrawals_db_service.GetUserRequestsRes.total_num', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error', full_name='io.lightcone.services.onchain_withdrawals_db_service.GetUserRequestsRes.error', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=247,
  serialized_end=405,
)


_GETREQUESTSRES = _descriptor.Descriptor(
  name='GetRequestsRes',
  full_name='io.lightcone.services.onchain_withdrawals_db_service.GetRequestsRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='requests', full_name='io.lightcone.services.onchain_withdrawals_db_service.GetRequestsRes.requests', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error', full_name='io.lightcone.services.onchain_withdrawals_db_service.GetRequestsRes.error', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=408,
  serialized_end=543,
)


_SUBMITREQUESTSREQ = _descriptor.Descriptor(
  name='SubmitRequestsReq',
  full_name='io.lightcone.services.onchain_withdrawals_db_service.SubmitRequestsReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='requests', full_name='io.lightcone.services.onchain_withdrawals_db_service.SubmitRequestsReq.requests', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=545,
  serialized_end=636,
)

_GETUSERREQUESTSRES.fields_by_name['requests'].message_type = data__requests__pb2._ONCHAINWITHDRAWALREQUEST
_GETUSERREQUESTSRES.fields_by_name['error'].message_type = data__types__pb2._ERROR
_GETREQUESTSRES.fields_by_name['requests'].message_type = data__requests__pb2._ONCHAINWITHDRAWALREQUEST
_GETREQUESTSRES.fields_by_name['error'].message_type = data__types__pb2._ERROR
_SUBMITREQUESTSREQ.fields_by_name['requests'].message_type = data__requests__pb2._ONCHAINWITHDRAWALREQUEST
DESCRIPTOR.message_types_by_name['GetUserRequestsRes'] = _GETUSERREQUESTSRES
DESCRIPTOR.message_types_by_name['GetRequestsRes'] = _GETREQUESTSRES
DESCRIPTOR.message_types_by_name['SubmitRequestsReq'] = _SUBMITREQUESTSREQ
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetUserRequestsRes = _reflection.GeneratedProtocolMessageType('GetUserRequestsRes', (_message.Message,), {
  'DESCRIPTOR' : _GETUSERREQUESTSRES,
  '__module__' : 'db_service_onchain_withdrawals_pb2'
  # @@protoc_insertion_point(class_scope:io.lightcone.services.onchain_withdrawals_db_service.GetUserRequestsRes)
  })
_sym_db.RegisterMessage(GetUserRequestsRes)

GetRequestsRes = _reflection.GeneratedProtocolMessageType('GetRequestsRes', (_message.Message,), {
  'DESCRIPTOR' : _GETREQUESTSRES,
  '__module__' : 'db_service_onchain_withdrawals_pb2'
  # @@protoc_insertion_point(class_scope:io.lightcone.services.onchain_withdrawals_db_service.GetRequestsRes)
  })
_sym_db.RegisterMessage(GetRequestsRes)

SubmitRequestsReq = _reflection.GeneratedProtocolMessageType('SubmitRequestsReq', (_message.Message,), {
  'DESCRIPTOR' : _SUBMITREQUESTSREQ,
  '__module__' : 'db_service_onchain_withdrawals_pb2'
  # @@protoc_insertion_point(class_scope:io.lightcone.services.onchain_withdrawals_db_service.SubmitRequestsReq)
  })
_sym_db.RegisterMessage(SubmitRequestsReq)


DESCRIPTOR._options = None

_ONCHAINWITHDRAWALSDBSERVICE = _descriptor.ServiceDescriptor(
  name='OnchainWithdrawalsDBService',
  full_name='io.lightcone.services.onchain_withdrawals_db_service.OnchainWithdrawalsDBService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=639,
  serialized_end=1530,
  methods=[
  _descriptor.MethodDescriptor(
    name='getUserRequests',
    full_name='io.lightcone.services.onchain_withdrawals_db_service.OnchainWithdrawalsDBService.getUserRequests',
    index=0,
    containing_service=None,
    input_type=db__service__request__common__pb2._GETUSERREQUESTSREQ,
    output_type=_GETUSERREQUESTSRES,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='getStats',
    full_name='io.lightcone.services.onchain_withdrawals_db_service.OnchainWithdrawalsDBService.getStats',
    index=1,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=db__service__request__common__pb2._REQUESTSTATS,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='getRequestByIds',
    full_name='io.lightcone.services.onchain_withdrawals_db_service.OnchainWithdrawalsDBService.getRequestByIds',
    index=2,
    containing_service=None,
    input_type=db__service__request__common__pb2._GETREQUESTSREQ,
    output_type=_GETREQUESTSRES,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='startAggregating',
    full_name='io.lightcone.services.onchain_withdrawals_db_service.OnchainWithdrawalsDBService.startAggregating',
    index=3,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='getByBlockId',
    full_name='io.lightcone.services.onchain_withdrawals_db_service.OnchainWithdrawalsDBService.getByBlockId',
    index=4,
    containing_service=None,
    input_type=db__service__request__common__pb2._GETBYBLOCKIDREQ,
    output_type=db__service__request__common__pb2._GETBYBLOCKIDRES,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='updateTxHashesAndStatus',
    full_name='io.lightcone.services.onchain_withdrawals_db_service.OnchainWithdrawalsDBService.updateTxHashesAndStatus',
    index=5,
    containing_service=None,
    input_type=db__service__request__common__pb2._UPDATETXHASHESREQ,
    output_type=db__service__request__common__pb2._UPDATETXHASHESRES,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='finishDistributed',
    full_name='io.lightcone.services.onchain_withdrawals_db_service.OnchainWithdrawalsDBService.finishDistributed',
    index=6,
    containing_service=None,
    input_type=db__service__request__common__pb2._FINISHDISTRIBUTEDREQ,
    output_type=db__service__request__common__pb2._FINISHDISTRIBUTEDRES,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ONCHAINWITHDRAWALSDBSERVICE)

DESCRIPTOR.services_by_name['OnchainWithdrawalsDBService'] = _ONCHAINWITHDRAWALSDBSERVICE

# @@protoc_insertion_point(module_scope)
