# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import db_service_market_view_pb2 as db__service__market__view__pb2


class MarketViewServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.getCandles = channel.unary_unary(
        '/io.lightcone.services.maket_view_service.MarketViewService/getCandles',
        request_serializer=db__service__market__view__pb2.GetCandlesReq.SerializeToString,
        response_deserializer=db__service__market__view__pb2.Candles.FromString,
        )
    self.getDepth = channel.unary_unary(
        '/io.lightcone.services.maket_view_service.MarketViewService/getDepth',
        request_serializer=db__service__market__view__pb2.GetDepthReq.SerializeToString,
        response_deserializer=db__service__market__view__pb2.Depth.FromString,
        )
    self.getTickers = channel.unary_unary(
        '/io.lightcone.services.maket_view_service.MarketViewService/getTickers',
        request_serializer=db__service__market__view__pb2.GetTickersReq.SerializeToString,
        response_deserializer=db__service__market__view__pb2.GetTickersRes.FromString,
        )


class MarketViewServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def getCandles(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getDepth(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getTickers(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_MarketViewServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'getCandles': grpc.unary_unary_rpc_method_handler(
          servicer.getCandles,
          request_deserializer=db__service__market__view__pb2.GetCandlesReq.FromString,
          response_serializer=db__service__market__view__pb2.Candles.SerializeToString,
      ),
      'getDepth': grpc.unary_unary_rpc_method_handler(
          servicer.getDepth,
          request_deserializer=db__service__market__view__pb2.GetDepthReq.FromString,
          response_serializer=db__service__market__view__pb2.Depth.SerializeToString,
      ),
      'getTickers': grpc.unary_unary_rpc_method_handler(
          servicer.getTickers,
          request_deserializer=db__service__market__view__pb2.GetTickersReq.FromString,
          response_serializer=db__service__market__view__pb2.GetTickersRes.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'io.lightcone.services.maket_view_service.MarketViewService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
