# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: db_service_external.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
import data_external_pb2 as data__external__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='db_service_external.proto',
  package='io.lightcone.services.external_service',
  syntax='proto3',
  serialized_options=_b('P\001'),
  serialized_pb=_b('\n\x19\x64\x62_service_external.proto\x12&io.lightcone.services.external_service\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x13\x64\x61ta_external.proto\"O\n\rGetTickersRes\x12>\n\x07tickers\x18\x01 \x03(\x0b\x32-.io.lightcone.data.external.TokenTickerRecord2\xad\x01\n\x0f\x45xternalService\x12=\n\x0bsyncTickers\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12[\n\ngetTickers\x12\x16.google.protobuf.Empty\x1a\x35.io.lightcone.services.external_service.GetTickersResB\x02P\x01\x62\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,google_dot_protobuf_dot_wrappers__pb2.DESCRIPTOR,data__external__pb2.DESCRIPTOR,])




_GETTICKERSRES = _descriptor.Descriptor(
  name='GetTickersRes',
  full_name='io.lightcone.services.external_service.GetTickersRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tickers', full_name='io.lightcone.services.external_service.GetTickersRes.tickers', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=151,
  serialized_end=230,
)

_GETTICKERSRES.fields_by_name['tickers'].message_type = data__external__pb2._TOKENTICKERRECORD
DESCRIPTOR.message_types_by_name['GetTickersRes'] = _GETTICKERSRES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetTickersRes = _reflection.GeneratedProtocolMessageType('GetTickersRes', (_message.Message,), {
  'DESCRIPTOR' : _GETTICKERSRES,
  '__module__' : 'db_service_external_pb2'
  # @@protoc_insertion_point(class_scope:io.lightcone.services.external_service.GetTickersRes)
  })
_sym_db.RegisterMessage(GetTickersRes)


DESCRIPTOR._options = None

_EXTERNALSERVICE = _descriptor.ServiceDescriptor(
  name='ExternalService',
  full_name='io.lightcone.services.external_service.ExternalService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=233,
  serialized_end=406,
  methods=[
  _descriptor.MethodDescriptor(
    name='syncTickers',
    full_name='io.lightcone.services.external_service.ExternalService.syncTickers',
    index=0,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='getTickers',
    full_name='io.lightcone.services.external_service.ExternalService.getTickers',
    index=1,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_GETTICKERSRES,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_EXTERNALSERVICE)

DESCRIPTOR.services_by_name['ExternalService'] = _EXTERNALSERVICE

# @@protoc_insertion_point(module_scope)
