# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import service_user_transaction_pb2 as service__user__transaction__pb2


class UserTransactionServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.getUserTransactions = channel.unary_unary(
        '/io.lightcone.services.service_user_transaction.UserTransactionService/getUserTransactions',
        request_serializer=service__user__transaction__pb2.GetUserTransactionsReq.SerializeToString,
        response_deserializer=service__user__transaction__pb2.GetUserTransactionsRes.FromString,
        )
    self.getOrder = channel.unary_unary(
        '/io.lightcone.services.service_user_transaction.UserTransactionService/getOrder',
        request_serializer=service__user__transaction__pb2.OrderReq.SerializeToString,
        response_deserializer=service__user__transaction__pb2.OrderRes.FromString,
        )
    self.getOrders = channel.unary_unary(
        '/io.lightcone.services.service_user_transaction.UserTransactionService/getOrders',
        request_serializer=service__user__transaction__pb2.OrdersReq.SerializeToString,
        response_deserializer=service__user__transaction__pb2.OrdersRes.FromString,
        )


class UserTransactionServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def getUserTransactions(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getOrder(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getOrders(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_UserTransactionServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'getUserTransactions': grpc.unary_unary_rpc_method_handler(
          servicer.getUserTransactions,
          request_deserializer=service__user__transaction__pb2.GetUserTransactionsReq.FromString,
          response_serializer=service__user__transaction__pb2.GetUserTransactionsRes.SerializeToString,
      ),
      'getOrder': grpc.unary_unary_rpc_method_handler(
          servicer.getOrder,
          request_deserializer=service__user__transaction__pb2.OrderReq.FromString,
          response_serializer=service__user__transaction__pb2.OrderRes.SerializeToString,
      ),
      'getOrders': grpc.unary_unary_rpc_method_handler(
          servicer.getOrders,
          request_deserializer=service__user__transaction__pb2.OrdersReq.FromString,
          response_serializer=service__user__transaction__pb2.OrdersRes.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'io.lightcone.services.service_user_transaction.UserTransactionService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
