# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service_prover.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
import data_blocks_pb2 as data__blocks__pb2
import data_types_pb2 as data__types__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='service_prover.proto',
  package='io.lightcone.services.prover_service',
  syntax='proto3',
  serialized_options=_b('P\001'),
  serialized_pb=_b('\n\x14service_prover.proto\x12$io.lightcone.services.prover_service\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x11\x64\x61ta_blocks.proto\x1a\x10\x64\x61ta_types.proto\"R\n\x0f\x43omputeProofReq\x12.\n\x05\x62lock\x18\x01 \x01(\x0b\x32\x1f.io.lightcone.data.blocks.Block\x12\x0f\n\x07task_id\x18\x02 \x01(\t\"q\n\x0f\x43omputeProofRes\x12\x13\n\x0b\x62lock_index\x18\x01 \x01(\x04\x12-\n\x05proof\x18\x02 \x01(\x0b\x32\x1e.io.lightcone.data.types.Proof\x12\x1a\n\x12proof_cost_seconds\x18\x03 \x01(\x04\"B\n\x10ValidateBlockReq\x12.\n\x05\x62lock\x18\x01 \x01(\x0b\x32\x1f.io.lightcone.data.blocks.Block\"X\n\x10ValidateBlockRes\x12\x13\n\x0b\x62lock_index\x18\x01 \x01(\x04\x12\x10\n\x08is_valid\x18\x02 \x01(\x08\x12\x1d\n\x15validate_cost_seconds\x18\x03 \x01(\x04\"\x1e\n\x0bKillTaskReq\x12\x0f\n\x07task_id\x18\x01 \x01(\t\" \n\rTaskStatusReq\x12\x0f\n\x07task_id\x18\x01 \x01(\t\"3\n\x0eTaskStatusResp\x12\x10\n\x08\x62lock_id\x18\x01 \x01(\x04\x12\x0f\n\x07runtime\x18\x02 \x01(\x04\x32\xcf\x02\n\rProverService\x12\x61\n\x0c\x63omputeProof\x12\x35.io.lightcone.services.prover_service.ComputeProofReq\x1a\x1a.google.protobuf.BoolValue\x12\x63\n\rvalidateBlock\x12\x36.io.lightcone.services.prover_service.ValidateBlockReq\x1a\x1a.google.protobuf.BoolValue\x12v\n\tgetStatus\x12\x33.io.lightcone.services.prover_service.TaskStatusReq\x1a\x34.io.lightcone.services.prover_service.TaskStatusRespB\x02P\x01\x62\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_wrappers__pb2.DESCRIPTOR,data__blocks__pb2.DESCRIPTOR,data__types__pb2.DESCRIPTOR,])




_COMPUTEPROOFREQ = _descriptor.Descriptor(
  name='ComputeProofReq',
  full_name='io.lightcone.services.prover_service.ComputeProofReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='block', full_name='io.lightcone.services.prover_service.ComputeProofReq.block', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='task_id', full_name='io.lightcone.services.prover_service.ComputeProofReq.task_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=131,
  serialized_end=213,
)


_COMPUTEPROOFRES = _descriptor.Descriptor(
  name='ComputeProofRes',
  full_name='io.lightcone.services.prover_service.ComputeProofRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='block_index', full_name='io.lightcone.services.prover_service.ComputeProofRes.block_index', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='proof', full_name='io.lightcone.services.prover_service.ComputeProofRes.proof', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='proof_cost_seconds', full_name='io.lightcone.services.prover_service.ComputeProofRes.proof_cost_seconds', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=215,
  serialized_end=328,
)


_VALIDATEBLOCKREQ = _descriptor.Descriptor(
  name='ValidateBlockReq',
  full_name='io.lightcone.services.prover_service.ValidateBlockReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='block', full_name='io.lightcone.services.prover_service.ValidateBlockReq.block', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=330,
  serialized_end=396,
)


_VALIDATEBLOCKRES = _descriptor.Descriptor(
  name='ValidateBlockRes',
  full_name='io.lightcone.services.prover_service.ValidateBlockRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='block_index', full_name='io.lightcone.services.prover_service.ValidateBlockRes.block_index', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='is_valid', full_name='io.lightcone.services.prover_service.ValidateBlockRes.is_valid', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='validate_cost_seconds', full_name='io.lightcone.services.prover_service.ValidateBlockRes.validate_cost_seconds', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=398,
  serialized_end=486,
)


_KILLTASKREQ = _descriptor.Descriptor(
  name='KillTaskReq',
  full_name='io.lightcone.services.prover_service.KillTaskReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='task_id', full_name='io.lightcone.services.prover_service.KillTaskReq.task_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=488,
  serialized_end=518,
)


_TASKSTATUSREQ = _descriptor.Descriptor(
  name='TaskStatusReq',
  full_name='io.lightcone.services.prover_service.TaskStatusReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='task_id', full_name='io.lightcone.services.prover_service.TaskStatusReq.task_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=520,
  serialized_end=552,
)


_TASKSTATUSRESP = _descriptor.Descriptor(
  name='TaskStatusResp',
  full_name='io.lightcone.services.prover_service.TaskStatusResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='block_id', full_name='io.lightcone.services.prover_service.TaskStatusResp.block_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='runtime', full_name='io.lightcone.services.prover_service.TaskStatusResp.runtime', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=554,
  serialized_end=605,
)

_COMPUTEPROOFREQ.fields_by_name['block'].message_type = data__blocks__pb2._BLOCK
_COMPUTEPROOFRES.fields_by_name['proof'].message_type = data__types__pb2._PROOF
_VALIDATEBLOCKREQ.fields_by_name['block'].message_type = data__blocks__pb2._BLOCK
DESCRIPTOR.message_types_by_name['ComputeProofReq'] = _COMPUTEPROOFREQ
DESCRIPTOR.message_types_by_name['ComputeProofRes'] = _COMPUTEPROOFRES
DESCRIPTOR.message_types_by_name['ValidateBlockReq'] = _VALIDATEBLOCKREQ
DESCRIPTOR.message_types_by_name['ValidateBlockRes'] = _VALIDATEBLOCKRES
DESCRIPTOR.message_types_by_name['KillTaskReq'] = _KILLTASKREQ
DESCRIPTOR.message_types_by_name['TaskStatusReq'] = _TASKSTATUSREQ
DESCRIPTOR.message_types_by_name['TaskStatusResp'] = _TASKSTATUSRESP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ComputeProofReq = _reflection.GeneratedProtocolMessageType('ComputeProofReq', (_message.Message,), {
  'DESCRIPTOR' : _COMPUTEPROOFREQ,
  '__module__' : 'service_prover_pb2'
  # @@protoc_insertion_point(class_scope:io.lightcone.services.prover_service.ComputeProofReq)
  })
_sym_db.RegisterMessage(ComputeProofReq)

ComputeProofRes = _reflection.GeneratedProtocolMessageType('ComputeProofRes', (_message.Message,), {
  'DESCRIPTOR' : _COMPUTEPROOFRES,
  '__module__' : 'service_prover_pb2'
  # @@protoc_insertion_point(class_scope:io.lightcone.services.prover_service.ComputeProofRes)
  })
_sym_db.RegisterMessage(ComputeProofRes)

ValidateBlockReq = _reflection.GeneratedProtocolMessageType('ValidateBlockReq', (_message.Message,), {
  'DESCRIPTOR' : _VALIDATEBLOCKREQ,
  '__module__' : 'service_prover_pb2'
  # @@protoc_insertion_point(class_scope:io.lightcone.services.prover_service.ValidateBlockReq)
  })
_sym_db.RegisterMessage(ValidateBlockReq)

ValidateBlockRes = _reflection.GeneratedProtocolMessageType('ValidateBlockRes', (_message.Message,), {
  'DESCRIPTOR' : _VALIDATEBLOCKRES,
  '__module__' : 'service_prover_pb2'
  # @@protoc_insertion_point(class_scope:io.lightcone.services.prover_service.ValidateBlockRes)
  })
_sym_db.RegisterMessage(ValidateBlockRes)

KillTaskReq = _reflection.GeneratedProtocolMessageType('KillTaskReq', (_message.Message,), {
  'DESCRIPTOR' : _KILLTASKREQ,
  '__module__' : 'service_prover_pb2'
  # @@protoc_insertion_point(class_scope:io.lightcone.services.prover_service.KillTaskReq)
  })
_sym_db.RegisterMessage(KillTaskReq)

TaskStatusReq = _reflection.GeneratedProtocolMessageType('TaskStatusReq', (_message.Message,), {
  'DESCRIPTOR' : _TASKSTATUSREQ,
  '__module__' : 'service_prover_pb2'
  # @@protoc_insertion_point(class_scope:io.lightcone.services.prover_service.TaskStatusReq)
  })
_sym_db.RegisterMessage(TaskStatusReq)

TaskStatusResp = _reflection.GeneratedProtocolMessageType('TaskStatusResp', (_message.Message,), {
  'DESCRIPTOR' : _TASKSTATUSRESP,
  '__module__' : 'service_prover_pb2'
  # @@protoc_insertion_point(class_scope:io.lightcone.services.prover_service.TaskStatusResp)
  })
_sym_db.RegisterMessage(TaskStatusResp)


DESCRIPTOR._options = None

_PROVERSERVICE = _descriptor.ServiceDescriptor(
  name='ProverService',
  full_name='io.lightcone.services.prover_service.ProverService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=608,
  serialized_end=943,
  methods=[
  _descriptor.MethodDescriptor(
    name='computeProof',
    full_name='io.lightcone.services.prover_service.ProverService.computeProof',
    index=0,
    containing_service=None,
    input_type=_COMPUTEPROOFREQ,
    output_type=google_dot_protobuf_dot_wrappers__pb2._BOOLVALUE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='validateBlock',
    full_name='io.lightcone.services.prover_service.ProverService.validateBlock',
    index=1,
    containing_service=None,
    input_type=_VALIDATEBLOCKREQ,
    output_type=google_dot_protobuf_dot_wrappers__pb2._BOOLVALUE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='getStatus',
    full_name='io.lightcone.services.prover_service.ProverService.getStatus',
    index=2,
    containing_service=None,
    input_type=_TASKSTATUSREQ,
    output_type=_TASKSTATUSRESP,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PROVERSERVICE)

DESCRIPTOR.services_by_name['ProverService'] = _PROVERSERVICE

# @@protoc_insertion_point(module_scope)
