# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
import service_blocks_pb2 as service__blocks__pb2


class BlocksServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.notifyProofCompleted = channel.unary_unary(
        '/io.lightcone.services.blocks_service.BlocksService/notifyProofCompleted',
        request_serializer=service__blocks__pb2.NotifyCompletedEvent.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_wrappers__pb2.BoolValue.FromString,
        )
    self.getRequestProcessedInBlock = channel.unary_unary(
        '/io.lightcone.services.blocks_service.BlocksService/getRequestProcessedInBlock',
        request_serializer=service__blocks__pb2.GetRequestProcessedInBlockReq.SerializeToString,
        response_deserializer=service__blocks__pb2.GetRequestProcessedInBlockRes.FromString,
        )


class BlocksServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def notifyProofCompleted(self, request, context):
    """prover worker call this API when proving successfully
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getRequestProcessedInBlock(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_BlocksServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'notifyProofCompleted': grpc.unary_unary_rpc_method_handler(
          servicer.notifyProofCompleted,
          request_deserializer=service__blocks__pb2.NotifyCompletedEvent.FromString,
          response_serializer=google_dot_protobuf_dot_wrappers__pb2.BoolValue.SerializeToString,
      ),
      'getRequestProcessedInBlock': grpc.unary_unary_rpc_method_handler(
          servicer.getRequestProcessedInBlock,
          request_deserializer=service__blocks__pb2.GetRequestProcessedInBlockReq.FromString,
          response_serializer=service__blocks__pb2.GetRequestProcessedInBlockRes.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'io.lightcone.services.blocks_service.BlocksService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
