# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service_onchain_transaction.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='service_onchain_transaction.proto',
  package='io.lightcone.services.onchain_transaction_service',
  syntax='proto3',
  serialized_options=_b('P\001'),
  serialized_pb=_b('\n!service_onchain_transaction.proto\x12\x31io.lightcone.services.onchain_transaction_service2\x1b\n\x19OnchainTransactionServiceB\x02P\x01\x62\x06proto3')
)



_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None

_ONCHAINTRANSACTIONSERVICE = _descriptor.ServiceDescriptor(
  name='OnchainTransactionService',
  full_name='io.lightcone.services.onchain_transaction_service.OnchainTransactionService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=88,
  serialized_end=115,
  methods=[
])
_sym_db.RegisterServiceDescriptor(_ONCHAINTRANSACTIONSERVICE)

DESCRIPTOR.services_by_name['OnchainTransactionService'] = _ONCHAINTRANSACTIONSERVICE

# @@protoc_insertion_point(module_scope)
