# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import data_order_pb2 as data__order__pb2
import data_requests_pb2 as data__requests__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
import service_dex_pb2 as service__dex__pb2


class DexServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.getDexConfigurations = channel.unary_unary(
        '/io.lightcone.dex.DexService/getDexConfigurations',
        request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        response_deserializer=service__dex__pb2.DexConfigurations.FromString,
        )
    self.getMarkets = channel.unary_unary(
        '/io.lightcone.dex.DexService/getMarkets',
        request_serializer=service__dex__pb2.GetMarketsReq.SerializeToString,
        response_deserializer=service__dex__pb2.GetMarketsRes.FromString,
        )
    self.getMarketFills = channel.unary_unary(
        '/io.lightcone.dex.DexService/getMarketFills',
        request_serializer=service__dex__pb2.GetMarketFillsReq.SerializeToString,
        response_deserializer=service__dex__pb2.GetFillsRes.FromString,
        )
    self.getCandles = channel.unary_unary(
        '/io.lightcone.dex.DexService/getCandles',
        request_serializer=service__dex__pb2.GetCandlesReq.SerializeToString,
        response_deserializer=service__dex__pb2.Candles.FromString,
        )
    self.getAccountId = channel.unary_unary(
        '/io.lightcone.dex.DexService/getAccountId',
        request_serializer=google_dot_protobuf_dot_wrappers__pb2.StringValue.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_wrappers__pb2.UInt64Value.FromString,
        )
    self.getAccountById = channel.unary_unary(
        '/io.lightcone.dex.DexService/getAccountById',
        request_serializer=google_dot_protobuf_dot_wrappers__pb2.UInt64Value.SerializeToString,
        response_deserializer=service__dex__pb2.Account.FromString,
        )
    self.getAvailableBalance = channel.unary_unary(
        '/io.lightcone.dex.DexService/getAvailableBalance',
        request_serializer=service__dex__pb2.GetAvailableBalanceReq.SerializeToString,
        response_deserializer=service__dex__pb2.GetAvailableBalanceRes.FromString,
        )
    self.getUserOrders = channel.unary_unary(
        '/io.lightcone.dex.DexService/getUserOrders',
        request_serializer=service__dex__pb2.GetUserOrdersReq.SerializeToString,
        response_deserializer=service__dex__pb2.GetUserOrdersRes.FromString,
        )
    self.getUserFills = channel.unary_unary(
        '/io.lightcone.dex.DexService/getUserFills',
        request_serializer=service__dex__pb2.GetUserFillsReq.SerializeToString,
        response_deserializer=service__dex__pb2.GetFillsRes.FromString,
        )
    self.getUserTransfers = channel.unary_unary(
        '/io.lightcone.dex.DexService/getUserTransfers',
        request_serializer=service__dex__pb2.GetUserTransfersReq.SerializeToString,
        response_deserializer=service__dex__pb2.GetUserTransfersRes.FromString,
        )
    self.getNextOrderId = channel.unary_unary(
        '/io.lightcone.dex.DexService/getNextOrderId',
        request_serializer=service__dex__pb2.GetNextOrderIdReq.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_wrappers__pb2.UInt32Value.FromString,
        )
    self.submitOrder = channel.unary_unary(
        '/io.lightcone.dex.DexService/submitOrder',
        request_serializer=data__order__pb2.Order.SerializeToString,
        response_deserializer=service__dex__pb2.SubmitOrderRes.FromString,
        )
    self.cancelOrder = channel.unary_unary(
        '/io.lightcone.dex.DexService/cancelOrder',
        request_serializer=service__dex__pb2.SimpleOrderCancellationReq.SerializeToString,
        response_deserializer=service__dex__pb2.CancelOrderRes.FromString,
        )
    self.submitOrderCancellation = channel.unary_unary(
        '/io.lightcone.dex.DexService/submitOrderCancellation',
        request_serializer=data__requests__pb2.OrderCancellationRequest.SerializeToString,
        response_deserializer=service__dex__pb2.CancelOrderRes.FromString,
        )
    self.submitOffchainWithdrawal = channel.unary_unary(
        '/io.lightcone.dex.DexService/submitOffchainWithdrawal',
        request_serializer=data__requests__pb2.OffchainWithdrawalRequest.SerializeToString,
        response_deserializer=service__dex__pb2.OffchainWithdrawalalRes.FromString,
        )


class DexServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def getDexConfigurations(self, request, context):
    """queries
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getMarkets(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getMarketFills(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getCandles(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getAccountId(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getAccountById(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getAvailableBalance(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getUserOrders(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getUserFills(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getUserTransfers(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getNextOrderId(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def submitOrder(self, request, context):
    """order operations
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def cancelOrder(self, request, context):
    """Cancel orders by marking them obsoleted in database, not to be included in blocks.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def submitOrderCancellation(self, request, context):
    """Submit an offchain order cancellation request, will make into blocks.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def submitOffchainWithdrawal(self, request, context):
    """Submit an offchain withdrawal request, will make into blocks.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_DexServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'getDexConfigurations': grpc.unary_unary_rpc_method_handler(
          servicer.getDexConfigurations,
          request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
          response_serializer=service__dex__pb2.DexConfigurations.SerializeToString,
      ),
      'getMarkets': grpc.unary_unary_rpc_method_handler(
          servicer.getMarkets,
          request_deserializer=service__dex__pb2.GetMarketsReq.FromString,
          response_serializer=service__dex__pb2.GetMarketsRes.SerializeToString,
      ),
      'getMarketFills': grpc.unary_unary_rpc_method_handler(
          servicer.getMarketFills,
          request_deserializer=service__dex__pb2.GetMarketFillsReq.FromString,
          response_serializer=service__dex__pb2.GetFillsRes.SerializeToString,
      ),
      'getCandles': grpc.unary_unary_rpc_method_handler(
          servicer.getCandles,
          request_deserializer=service__dex__pb2.GetCandlesReq.FromString,
          response_serializer=service__dex__pb2.Candles.SerializeToString,
      ),
      'getAccountId': grpc.unary_unary_rpc_method_handler(
          servicer.getAccountId,
          request_deserializer=google_dot_protobuf_dot_wrappers__pb2.StringValue.FromString,
          response_serializer=google_dot_protobuf_dot_wrappers__pb2.UInt64Value.SerializeToString,
      ),
      'getAccountById': grpc.unary_unary_rpc_method_handler(
          servicer.getAccountById,
          request_deserializer=google_dot_protobuf_dot_wrappers__pb2.UInt64Value.FromString,
          response_serializer=service__dex__pb2.Account.SerializeToString,
      ),
      'getAvailableBalance': grpc.unary_unary_rpc_method_handler(
          servicer.getAvailableBalance,
          request_deserializer=service__dex__pb2.GetAvailableBalanceReq.FromString,
          response_serializer=service__dex__pb2.GetAvailableBalanceRes.SerializeToString,
      ),
      'getUserOrders': grpc.unary_unary_rpc_method_handler(
          servicer.getUserOrders,
          request_deserializer=service__dex__pb2.GetUserOrdersReq.FromString,
          response_serializer=service__dex__pb2.GetUserOrdersRes.SerializeToString,
      ),
      'getUserFills': grpc.unary_unary_rpc_method_handler(
          servicer.getUserFills,
          request_deserializer=service__dex__pb2.GetUserFillsReq.FromString,
          response_serializer=service__dex__pb2.GetFillsRes.SerializeToString,
      ),
      'getUserTransfers': grpc.unary_unary_rpc_method_handler(
          servicer.getUserTransfers,
          request_deserializer=service__dex__pb2.GetUserTransfersReq.FromString,
          response_serializer=service__dex__pb2.GetUserTransfersRes.SerializeToString,
      ),
      'getNextOrderId': grpc.unary_unary_rpc_method_handler(
          servicer.getNextOrderId,
          request_deserializer=service__dex__pb2.GetNextOrderIdReq.FromString,
          response_serializer=google_dot_protobuf_dot_wrappers__pb2.UInt32Value.SerializeToString,
      ),
      'submitOrder': grpc.unary_unary_rpc_method_handler(
          servicer.submitOrder,
          request_deserializer=data__order__pb2.Order.FromString,
          response_serializer=service__dex__pb2.SubmitOrderRes.SerializeToString,
      ),
      'cancelOrder': grpc.unary_unary_rpc_method_handler(
          servicer.cancelOrder,
          request_deserializer=service__dex__pb2.SimpleOrderCancellationReq.FromString,
          response_serializer=service__dex__pb2.CancelOrderRes.SerializeToString,
      ),
      'submitOrderCancellation': grpc.unary_unary_rpc_method_handler(
          servicer.submitOrderCancellation,
          request_deserializer=data__requests__pb2.OrderCancellationRequest.FromString,
          response_serializer=service__dex__pb2.CancelOrderRes.SerializeToString,
      ),
      'submitOffchainWithdrawal': grpc.unary_unary_rpc_method_handler(
          servicer.submitOffchainWithdrawal,
          request_deserializer=data__requests__pb2.OffchainWithdrawalRequest.FromString,
          response_serializer=service__dex__pb2.OffchainWithdrawalalRes.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'io.lightcone.dex.DexService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
