# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service_coordinator.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import data_types_pb2 as data__types__pb2
import data_requests_pb2 as data__requests__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='service_coordinator.proto',
  package='io.lightcone.services.coordinator_service',
  syntax='proto3',
  serialized_options=_b('P\001'),
  serialized_pb=_b('\n\x19service_coordinator.proto\x12)io.lightcone.services.coordinator_service\x1a\x10\x64\x61ta_types.proto\x1a\x13\x64\x61ta_requests.proto\"\xfb\x02\n\x15RequestProcessedState\x12\x11\n\tglobal_id\x18\x01 \x01(\x04\x12:\n\x0crequest_type\x18\x02 \x01(\x0e\x32$.io.lightcone.data.types.RequestType\x12\x12\n\nrequest_id\x18\x03 \x01(\x04\x12\x41\n\x0erequest_status\x18\x04 \x01(\x0e\x32).io.lightcone.data.requests.RequestStatus\x12\x34\n\x07request\x18\x05 \x01(\x0b\x32#.io.lightcone.data.requests.Request\x12H\n\x0eprocessed_data\x18\x06 \x01(\x0b\x32\x30.io.lightcone.data.requests.RequestProcessedData\x12\x12\n\nhas_sended\x18\x07 \x01(\x08\x12\x13\n\x0b\x63reate_time\x18\n \x01(\x03\x12\x13\n\x0bupdate_time\x18\x0b \x01(\x03\"a\n\x0eGetGlobalIdReq\x12:\n\x0crequest_type\x18\x01 \x01(\x0e\x32$.io.lightcone.data.types.RequestType\x12\x13\n\x0brequest_ids\x18\x02 \x03(\x03\"\xbc\x01\n\x0eGetGlobalIdRes\x12O\n\x03ids\x18\x01 \x03(\x0b\x32\x42.io.lightcone.services.coordinator_service.GetGlobalIdRes.IdsEntry\x12-\n\x05\x65rror\x18\x02 \x01(\x0b\x32\x1e.io.lightcone.data.types.Error\x1a*\n\x08IdsEntry\x12\x0b\n\x03key\x18\x01 \x01(\x03\x12\r\n\x05value\x18\x02 \x01(\x03:\x02\x38\x01\"\xaf\x01\n\x1aRequestProcessedStateEvent\x12\x11\n\tglobal_id\x18\x01 \x01(\x04\x12\x34\n\x07request\x18\x02 \x01(\x0b\x32#.io.lightcone.data.requests.Request\x12H\n\x0eprocessed_data\x18\x05 \x01(\x0b\x32\x30.io.lightcone.data.requests.RequestProcessedData2\x9a\x01\n\x12\x43oordinatorService\x12\x83\x01\n\x0bgetGlobalId\x12\x39.io.lightcone.services.coordinator_service.GetGlobalIdReq\x1a\x39.io.lightcone.services.coordinator_service.GetGlobalIdResB\x02P\x01\x62\x06proto3')
  ,
  dependencies=[data__types__pb2.DESCRIPTOR,data__requests__pb2.DESCRIPTOR,])




_REQUESTPROCESSEDSTATE = _descriptor.Descriptor(
  name='RequestProcessedState',
  full_name='io.lightcone.services.coordinator_service.RequestProcessedState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='global_id', full_name='io.lightcone.services.coordinator_service.RequestProcessedState.global_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='request_type', full_name='io.lightcone.services.coordinator_service.RequestProcessedState.request_type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='request_id', full_name='io.lightcone.services.coordinator_service.RequestProcessedState.request_id', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='request_status', full_name='io.lightcone.services.coordinator_service.RequestProcessedState.request_status', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='request', full_name='io.lightcone.services.coordinator_service.RequestProcessedState.request', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='processed_data', full_name='io.lightcone.services.coordinator_service.RequestProcessedState.processed_data', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='has_sended', full_name='io.lightcone.services.coordinator_service.RequestProcessedState.has_sended', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='create_time', full_name='io.lightcone.services.coordinator_service.RequestProcessedState.create_time', index=7,
      number=10, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='update_time', full_name='io.lightcone.services.coordinator_service.RequestProcessedState.update_time', index=8,
      number=11, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=112,
  serialized_end=491,
)


_GETGLOBALIDREQ = _descriptor.Descriptor(
  name='GetGlobalIdReq',
  full_name='io.lightcone.services.coordinator_service.GetGlobalIdReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='request_type', full_name='io.lightcone.services.coordinator_service.GetGlobalIdReq.request_type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='request_ids', full_name='io.lightcone.services.coordinator_service.GetGlobalIdReq.request_ids', index=1,
      number=2, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=493,
  serialized_end=590,
)


_GETGLOBALIDRES_IDSENTRY = _descriptor.Descriptor(
  name='IdsEntry',
  full_name='io.lightcone.services.coordinator_service.GetGlobalIdRes.IdsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='io.lightcone.services.coordinator_service.GetGlobalIdRes.IdsEntry.key', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='io.lightcone.services.coordinator_service.GetGlobalIdRes.IdsEntry.value', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=739,
  serialized_end=781,
)

_GETGLOBALIDRES = _descriptor.Descriptor(
  name='GetGlobalIdRes',
  full_name='io.lightcone.services.coordinator_service.GetGlobalIdRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ids', full_name='io.lightcone.services.coordinator_service.GetGlobalIdRes.ids', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error', full_name='io.lightcone.services.coordinator_service.GetGlobalIdRes.error', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_GETGLOBALIDRES_IDSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=593,
  serialized_end=781,
)


_REQUESTPROCESSEDSTATEEVENT = _descriptor.Descriptor(
  name='RequestProcessedStateEvent',
  full_name='io.lightcone.services.coordinator_service.RequestProcessedStateEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='global_id', full_name='io.lightcone.services.coordinator_service.RequestProcessedStateEvent.global_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='request', full_name='io.lightcone.services.coordinator_service.RequestProcessedStateEvent.request', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='processed_data', full_name='io.lightcone.services.coordinator_service.RequestProcessedStateEvent.processed_data', index=2,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=784,
  serialized_end=959,
)

_REQUESTPROCESSEDSTATE.fields_by_name['request_type'].enum_type = data__types__pb2._REQUESTTYPE
_REQUESTPROCESSEDSTATE.fields_by_name['request_status'].enum_type = data__requests__pb2._REQUESTSTATUS
_REQUESTPROCESSEDSTATE.fields_by_name['request'].message_type = data__requests__pb2._REQUEST
_REQUESTPROCESSEDSTATE.fields_by_name['processed_data'].message_type = data__requests__pb2._REQUESTPROCESSEDDATA
_GETGLOBALIDREQ.fields_by_name['request_type'].enum_type = data__types__pb2._REQUESTTYPE
_GETGLOBALIDRES_IDSENTRY.containing_type = _GETGLOBALIDRES
_GETGLOBALIDRES.fields_by_name['ids'].message_type = _GETGLOBALIDRES_IDSENTRY
_GETGLOBALIDRES.fields_by_name['error'].message_type = data__types__pb2._ERROR
_REQUESTPROCESSEDSTATEEVENT.fields_by_name['request'].message_type = data__requests__pb2._REQUEST
_REQUESTPROCESSEDSTATEEVENT.fields_by_name['processed_data'].message_type = data__requests__pb2._REQUESTPROCESSEDDATA
DESCRIPTOR.message_types_by_name['RequestProcessedState'] = _REQUESTPROCESSEDSTATE
DESCRIPTOR.message_types_by_name['GetGlobalIdReq'] = _GETGLOBALIDREQ
DESCRIPTOR.message_types_by_name['GetGlobalIdRes'] = _GETGLOBALIDRES
DESCRIPTOR.message_types_by_name['RequestProcessedStateEvent'] = _REQUESTPROCESSEDSTATEEVENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RequestProcessedState = _reflection.GeneratedProtocolMessageType('RequestProcessedState', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTPROCESSEDSTATE,
  '__module__' : 'service_coordinator_pb2'
  # @@protoc_insertion_point(class_scope:io.lightcone.services.coordinator_service.RequestProcessedState)
  })
_sym_db.RegisterMessage(RequestProcessedState)

GetGlobalIdReq = _reflection.GeneratedProtocolMessageType('GetGlobalIdReq', (_message.Message,), {
  'DESCRIPTOR' : _GETGLOBALIDREQ,
  '__module__' : 'service_coordinator_pb2'
  # @@protoc_insertion_point(class_scope:io.lightcone.services.coordinator_service.GetGlobalIdReq)
  })
_sym_db.RegisterMessage(GetGlobalIdReq)

GetGlobalIdRes = _reflection.GeneratedProtocolMessageType('GetGlobalIdRes', (_message.Message,), {

  'IdsEntry' : _reflection.GeneratedProtocolMessageType('IdsEntry', (_message.Message,), {
    'DESCRIPTOR' : _GETGLOBALIDRES_IDSENTRY,
    '__module__' : 'service_coordinator_pb2'
    # @@protoc_insertion_point(class_scope:io.lightcone.services.coordinator_service.GetGlobalIdRes.IdsEntry)
    })
  ,
  'DESCRIPTOR' : _GETGLOBALIDRES,
  '__module__' : 'service_coordinator_pb2'
  # @@protoc_insertion_point(class_scope:io.lightcone.services.coordinator_service.GetGlobalIdRes)
  })
_sym_db.RegisterMessage(GetGlobalIdRes)
_sym_db.RegisterMessage(GetGlobalIdRes.IdsEntry)

RequestProcessedStateEvent = _reflection.GeneratedProtocolMessageType('RequestProcessedStateEvent', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTPROCESSEDSTATEEVENT,
  '__module__' : 'service_coordinator_pb2'
  # @@protoc_insertion_point(class_scope:io.lightcone.services.coordinator_service.RequestProcessedStateEvent)
  })
_sym_db.RegisterMessage(RequestProcessedStateEvent)


DESCRIPTOR._options = None
_GETGLOBALIDRES_IDSENTRY._options = None

_COORDINATORSERVICE = _descriptor.ServiceDescriptor(
  name='CoordinatorService',
  full_name='io.lightcone.services.coordinator_service.CoordinatorService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=962,
  serialized_end=1116,
  methods=[
  _descriptor.MethodDescriptor(
    name='getGlobalId',
    full_name='io.lightcone.services.coordinator_service.CoordinatorService.getGlobalId',
    index=0,
    containing_service=None,
    input_type=_GETGLOBALIDREQ,
    output_type=_GETGLOBALIDRES,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_COORDINATORSERVICE)

DESCRIPTOR.services_by_name['CoordinatorService'] = _COORDINATORSERVICE

# @@protoc_insertion_point(module_scope)
