# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import service_health_checking_pb2 as service__health__checking__pb2


class HealthStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Check = channel.unary_unary(
        '/io.lightcone.services.health_checking.Health/Check',
        request_serializer=service__health__checking__pb2.HealthCheckRequest.SerializeToString,
        response_deserializer=service__health__checking__pb2.HealthCheckResponse.FromString,
        )
    self.Watch = channel.unary_stream(
        '/io.lightcone.services.health_checking.Health/Watch',
        request_serializer=service__health__checking__pb2.HealthCheckRequest.SerializeToString,
        response_deserializer=service__health__checking__pb2.HealthCheckResponse.FromString,
        )


class HealthServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Check(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Watch(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_HealthServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Check': grpc.unary_unary_rpc_method_handler(
          servicer.Check,
          request_deserializer=service__health__checking__pb2.HealthCheckRequest.FromString,
          response_serializer=service__health__checking__pb2.HealthCheckResponse.SerializeToString,
      ),
      'Watch': grpc.unary_stream_rpc_method_handler(
          servicer.Watch,
          request_deserializer=service__health__checking__pb2.HealthCheckRequest.FromString,
          response_serializer=service__health__checking__pb2.HealthCheckResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'io.lightcone.services.health_checking.Health', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
