# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
import service_prover_pb2 as service__prover__pb2


class ProverServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.computeProof = channel.unary_unary(
        '/io.lightcone.services.prover_service.ProverService/computeProof',
        request_serializer=service__prover__pb2.ComputeProofReq.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_wrappers__pb2.BoolValue.FromString,
        )
    self.validateBlock = channel.unary_unary(
        '/io.lightcone.services.prover_service.ProverService/validateBlock',
        request_serializer=service__prover__pb2.ValidateBlockReq.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_wrappers__pb2.BoolValue.FromString,
        )
    self.getStatus = channel.unary_unary(
        '/io.lightcone.services.prover_service.ProverService/getStatus',
        request_serializer=service__prover__pb2.TaskStatusReq.SerializeToString,
        response_deserializer=service__prover__pb2.TaskStatusResp.FromString,
        )


class ProverServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def computeProof(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def validateBlock(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getStatus(self, request, context):
    """query blockId from current service
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ProverServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'computeProof': grpc.unary_unary_rpc_method_handler(
          servicer.computeProof,
          request_deserializer=service__prover__pb2.ComputeProofReq.FromString,
          response_serializer=google_dot_protobuf_dot_wrappers__pb2.BoolValue.SerializeToString,
      ),
      'validateBlock': grpc.unary_unary_rpc_method_handler(
          servicer.validateBlock,
          request_deserializer=service__prover__pb2.ValidateBlockReq.FromString,
          response_serializer=google_dot_protobuf_dot_wrappers__pb2.BoolValue.SerializeToString,
      ),
      'getStatus': grpc.unary_unary_rpc_method_handler(
          servicer.getStatus,
          request_deserializer=service__prover__pb2.TaskStatusReq.FromString,
          response_serializer=service__prover__pb2.TaskStatusResp.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'io.lightcone.services.prover_service.ProverService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
